<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-09-27T02:04:58Z" name="All Test Suite" finished-at="2019-09-27T02:05:02Z" duration-ms="4350">
    <groups>
    </groups>
    <test started-at="2019-09-27T02:04:58Z" name="login" finished-at="2019-09-27T02:05:00Z" duration-ms="2602">
      <class name="testObjects.LoginTest">
        <test-method signature="unsuccessfulLogin()[pri:0, instance:testObjects.LoginTest@2c3dec30]" started-at="2019-09-27T02:04:58Z" name="unsuccessfulLogin" finished-at="2019-09-27T02:04:58Z" duration-ms="929" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unsuccessfulLogin -->
        <test-method signature="successfulLogin()[pri:0, instance:testObjects.LoginTest@2c3dec30]" started-at="2019-09-27T02:04:58Z" name="successfulLogin" finished-at="2019-09-27T02:05:00Z" duration-ms="1081" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successfulLogin -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:testObjects.LoginTest@2c3dec30]" started-at="2019-09-27T02:05:00Z" name="closeBrowser" finished-at="2019-09-27T02:05:00Z" duration-ms="579" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testObjects.LoginTest -->
    </test> <!-- login -->
    <test started-at="2019-09-27T02:05:00Z" name="generate" finished-at="2019-09-27T02:05:02Z" duration-ms="1732">
      <class name="testObjects.GenerateTest">
        <test-method signature="generatePermanentPurchased()[pri:0, instance:testObjects.GenerateTest@841e575]" started-at="2019-09-27T02:05:00Z" name="generatePermanentPurchased" finished-at="2019-09-27T02:05:02Z" duration-ms="1729" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [License Management] but found [License Generation]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [License Management] but found [License Generation]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testObjects.LoginTest.successfulLogin(LoginTest.java:50)
at testObjects.GenerateTest.generatePermanentPurchased(GenerateTest.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generatePermanentPurchased -->
      </class> <!-- testObjects.GenerateTest -->
    </test> <!-- generate -->
  </suite> <!-- All Test Suite -->
</testng-results>
